osx_image: xcode8
language: objective-c
cache: cocoapods
podfile: Podfile

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
- pod install

script:
- set -o pipefail
- xcodebuild -workspace "Rate-iOS.xcworkspace" -scheme "Rate-iOS" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
- xcodebuild -workspace "Rate-iOS.xcworkspace" -scheme "Rate-iOS" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c